-- Insertar 10 registros en la tabla Products
INSERT INTO Products (name, description, stock, cost, price, currency, category)
VALUES
    ('Computadora Gaming', 'Potente computadora para juegos', 500, 1500.00, 1999.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Gaming')),
    ('Impresora Multifuncional', 'Impresora con funciones de escaneo y copiado', 200, 500.00, 699.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Software de Edición de Video', 'Programa para editar y crear videos profesionales', 300, 200.00, 299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Software')),
    ('Teléfono Inteligente', 'Teléfono móvil con funciones avanzadas', 1000, 800.00, 999.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Teléfono')),
    ('Monitor Curvo', 'Monitor con pantalla curva para una experiencia inmersiva', 700, 300.00, 499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Monitores')),
    ('Router Wi-Fi', 'Dispositivo para establecer una red inalámbrica', 400, 80.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Redes')),
    ('Disco Duro Externo', 'Almacenamiento portátil de alta capacidad', 600, 100.00, 149.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Almacenamiento')),
    ('Teclado Mecánico para Gaming', 'Teclado retroiluminado especialmente diseñado para juegos', 100, 50.00, 79.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Altavoces Bluetooth', 'Altavoces inalámbricos con conexión Bluetooth', 800, 60.00, 99.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Tableta Gráfica', 'Dispositivo para dibujar y diseñar en el computador', 150, 150.00, 249.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Tabletas'))
    ('Auriculares Inalámbricos', 'Auriculares con conexión Bluetooth', 400, 40.00, 69.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Cámara Digital', 'Cámara para capturar fotografías de alta calidad', 300, 250.00, 399.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Cámaras')),
    ('Laptop Ultraligera', 'Portátil liviano y de alto rendimiento', 200, 1200.00, 1499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Laptops')),
    ('Impresora 3D', 'Impresora que crea objetos tridimensionales', 100, 600.00, 799.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Smart TV', 'Televisor con acceso a aplicaciones y contenido en línea', 500, 700.00, 999.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'TV')),
    ('Mouse Gaming', 'Mouse con alta precisión para juegos', 800, 30.00, 49.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Bocinas de Escritorio', 'Altavoces para computadora de escritorio', 300, 20.00, 39.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('SSD Interno', 'Disco de estado sólido para mejorar la velocidad de almacenamiento', 400, 80.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Almacenamiento')),
    ('Webcam HD', 'Cámara para videollamadas y conferencias en alta definición', 200, 50.00, 79.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Proyector Portátil', 'Dispositivo para proyectar imágenes y videos', 150, 200.00, 349.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Proyectores')),
    ('Smartwatch', 'Reloj inteligente con funciones avanzadas', 300, 100.00, 149.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Impresora de Etiquetas', 'Impresora especializada en imprimir etiquetas', 150, 200.00, 299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Procesador de última generación', 'Unidad de procesamiento de alto rendimiento', 100, 300.00, 499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Componentes')),
    ('Módulo de Memoria RAM', 'Memoria adicional para mejorar el rendimiento del sistema', 400, 50.00, 89.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Componentes')),
    ('Smart Home Hub', 'Dispositivo central para controlar dispositivos inteligentes en el hogar', 200, 80.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Hogar')),
    ('Escáner de Documentos', 'Dispositivo para digitalizar documentos en papel', 300, 150.00, 249.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Cargador Portátil', 'Batería externa para cargar dispositivos móviles', 500, 30.00, 49.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Aire Acondicionado Inteligente', 'Aparato de climatización controlado desde el teléfono', 100, 500.00, 799.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Hogar')),
    ('Teclado y Mouse Inalámbrico', 'Set de teclado y mouse sin cables', 400, 40.00, 69.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Sistema de Sonido Envolvente', 'Altavoces para crear una experiencia de audio inmersiva', 200, 150.00, 249.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Cámara DSLR', 'Cámara profesional para fotografía', 50, 800.00, 1099.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Cámaras')),
    ('Smart TV', 'Televisor con funciones inteligentes y conectividad', 100, 600.00, 899.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Micrófono USB', 'Micrófono con conexión USB para grabación de audio', 200, 50.00, 79.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Proyector HD', 'Proyector de alta definición para presentaciones y entretenimiento', 150, 300.00, 499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Dispositivo de Almacenamiento SSD', 'Unidad de estado sólido para almacenamiento rápido', 300, 80.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Almacenamiento')),
    ('Impresora 3D', 'Impresora capaz de crear objetos tridimensionales', 50, 500.00, 799.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Smart Speaker', 'Altavoz inteligente con asistente virtual integrado', 100, 70.00, 109.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Ratón Gaming', 'Mouse diseñado especialmente para juegos', 200, 30.00, 49.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Laptop Ultrabook', 'Portátil delgado y ligero con alto rendimiento', 50, 1000.00, 1499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Computadoras')),
    ('Sistema de Seguridad para Hogar', 'Cámaras y sensores para proteger tu hogar', 100, 200.00, 299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Hogar')),
    ('Auriculares Inalámbricos', 'Auriculares con conexión Bluetooth', 300, 40.00, 69.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Tarjeta Gráfica', 'Componente para mejorar el rendimiento gráfico', 100, 300.00, 449.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Componentes')),
    ('Teclado y Mouse Inalámbricos', 'Combo de teclado y mouse sin cables', 200, 50.00, 79.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Repetidor de Señal Wi-Fi', 'Dispositivo para amplificar la señal inalámbrica', 150, 30.00, 49.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Redes')),
    ('Memoria RAM', 'Módulo de memoria para mejorar el rendimiento del computador', 500, 60.00, 99.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Componentes')),
    ('Monitor 4K', 'Monitor con resolución Ultra HD', 100, 400.00, 599.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Monitores')),
    ('Disco Duro Interno', 'Almacenamiento interno de alta capacidad', 400, 70.00, 119.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Almacenamiento')),
    ('Cámara de Seguridad', 'Cámara para vigilancia y seguridad', 200, 80.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Hogar')),
    ('Altavoces 2.1', 'Sistema de altavoces con subwoofer', 150, 50.00, 89.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Impresora Láser', 'Impresora de alta velocidad y calidad', 100, 150.00, 249.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Smartwatch', 'Reloj inteligente con funciones avanzadas', 300, 80.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Cámara Réflex', 'Cámara profesional para fotografía', 100, 600.00, 899.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Cámaras')),
    ('Memoria USB', 'Dispositivo de almacenamiento portátil', 500, 20.00, 39.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Almacenamiento')),
    ('Laptop Ultrabook', 'Computadora portátil ultradelgada y ligera', 200, 800.00, 1299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Computadoras')),
    ('Proyector Full HD', 'Proyector de alta definición para presentaciones y entretenimiento', 150, 300.00, 499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Impresora 3D', 'Impresora para crear objetos en 3D', 50, 400.00, 699.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Silla Gaming', 'Silla ergonómica para jugadores', 100, 150.00, 249.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Muebles')),
    ('Barra de Sonido', 'Altavoz para mejorar el sonido de la televisión', 200, 70.00, 119.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Micrófono USB', 'Micrófono de calidad para grabaciones y streaming', 300, 30.00, 59.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Monitor Portátil', 'Pantalla adicional portátil para laptops', 150, 200.00, 349.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Monitores')),
    ('Auriculares Inalámbricos', 'Auriculares con conexión Bluetooth', 500, 40.00, 79.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Smart TV 4K', 'Televisor inteligente con resolución 4K', 200, 700.00, 999.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Televisores')),
    ('Teclado Inalámbrico', 'Teclado sin cables para mayor comodidad', 300, 25.00, 49.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Cámara de Seguridad', 'Cámara de vigilancia para el hogar', 100, 50.00, 99.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Bocina Portátil', 'Altavoz compacto y portátil', 500, 20.00, 39.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Reproductor de Blu-ray', 'Dispositivo para reproducir películas en alta definición', 100, 70.00, 129.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Mochila para Laptop', 'Mochila diseñada para transportar laptops', 200, 30.00, 59.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Smart Speaker', 'Altavoz inteligente con asistente virtual', 150, 80.00, 149.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Cargador Portátil', 'Batería externa para cargar dispositivos móviles', 300, 15.00, 29.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Escáner de Documentos', 'Dispositivo para digitalizar documentos', 100, 60.00, 99.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Smartwatch', 'Reloj inteligente con funciones avanzadas', 300, 100.00, 199.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Cámara Réflex', 'Cámara fotográfica profesional', 150, 500.00, 799.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Cámaras')),
    ('Aspiradora Robótica', 'Aspiradora automática con navegación inteligente', 100, 200.00, 399.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrodomésticos')),
    ('Proyector HD', 'Proyector de alta definición para cine en casa', 200, 300.00, 499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Impresora 3D', 'Impresora que crea objetos tridimensionales', 50, 800.00, 1299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras')),
    ('Kit de Iluminación', 'Conjunto de luces para fotografía y video', 100, 150.00, 249.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Sistema de Sonido Surround', 'Conjunto de altavoces para una experiencia de audio envolvente', 80, 400.00, 699.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Micrófono de Condensador', 'Micrófono profesional para grabaciones de alta calidad', 200, 150.00, 299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Laptop Ultraligera', 'Portátil delgado y ligero para mayor movilidad', 150, 1000.00, 1499.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Computadoras')),
    ('Silla Gaming', 'Silla ergonómica para largas sesiones de juegos', 100, 200.00, 399.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Muebles')),
    ('Auriculares Inalámbricos', 'Auriculares con conexión Bluetooth', 500, 50.00, 99.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Audio')),
    ('Batería Externa', 'Dispositivo para cargar dispositivos móviles', 300, 30.00, 49.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Teclado Inalámbrico', 'Teclado sin cables para mayor comodidad', 200, 40.00, 79.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Pantalla de Proyección', 'Superficie para proyectar imágenes y videos', 100, 100.00, 199.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Cámara de Seguridad', 'Cámara de vigilancia para la seguridad del hogar', 150, 80.00, 149.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Lente Gran Angular', 'Lente fotográfico para capturar imágenes amplias', 100, 150.00, 299.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Accesorios')),
    ('Reproductor de Blu-ray', 'Dispositivo para reproducir películas en alta definición', 80, 60.00, 99.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Tarjeta de Memoria', 'Tarjeta de almacenamiento para cámaras y dispositivos', 200, 20.00, 39.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Almacenamiento')),
    ('Smart TV', 'Televisor con funciones inteligentes', 1000, 600.00, 999.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Electrónica')),
    ('Escáner de Documentos', 'Dispositivo para digitalizar documentos', 150, 100.00, 199.99, (SELECT id FROM CurrencyType WHERE currency = 'Córdobas'), (SELECT id FROM Category WHERE name = 'Impresoras'));


